### ISSUE TITLE
Brute warcasket pawns spawn with ranged weapons

### ISSUE THREAD

**Issue by SamaelGray** [AndroidQuazar/VanillaFactionsExpanded-Pirates#2]
As seen from the screenshot below, pawns that spawn with the Brute warcasket armor piece can spawn with ranged weapons equipped which the armor piece forbids them from shooting making the pawn useless in combat as a result...

Tested with both a CE and a non-CE modlist and the latest version of the mod, the same occurrence can happen via spawning a couple "VFEP_Veteran" pawns.

With CE:
![image](https://user-images.githubusercontent.com/56392968/174535522-6ab5a448-498a-4143-a47c-1c21f1b6b6c1.png)

Without CE:
![image](https://user-images.githubusercontent.com/56392968/174536071-a9a14d4e-5df2-4b80-8a62-0481c03f017a.png)

I'd suggest limiting the brute warcasket armor piece to only be available to melee warcasket pawnkinds.

**Comment by SamaelGray** [comment]
Also on another note, the Siegebreaker shoulders' description states `augmented with improved power conduits that increase shield recharge rate` but the equippedStatOffsets lacks the bonus recharge rate.

![image](https://user-images.githubusercontent.com/56392968/174650694-12ee06b0-1e6a-4fca-b4a4-fdecf3337824.png)

**Comment by xrushha** [comment]
Fixed all of these in the latest commits. Thank you for reporting!
